version: 2

models:
  - name: user
    description: any post
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: email
        description: email
        tests:
          - unique
          - not_null
      - name: username
        description: unique name of customer
        tests:
          - not_null
          - unique

  - name: user_posts
    description: user with their posts
    columns:
      - name: post_id
        tests:
          - unique
      - name: content
        type: text
        description: post_text
      - name: user_id
      - name: user_name

  - name: post_with_comments
    description: users with their posts and comments to them
    columns:
      - name: post_text
      - name: post_id
      - name: user_id
      - name: username
      - name: post_text
      - name: comment_id
        tests:
          - unique
      - name: comment_text

  - name: user_comments
    description: all comments by user
    columns:
      - name: user_id
        type: bigint
      - name: comment_id
        type: bigint
        tests:
          - unique
      - name: comment_text
        type: text
        tests:
          - not_null
      - name: username
        type: text

  - name: user_content
    description: All types of content, generated by user
    columns:
      - name: user_id
        type: bigint
      - name: content
        type: text
        description: text of content
      - name: content_type
        type: varchar
        description: type of content